### PR TITLE
Handling unsigned numbers better in jextract

### LINKED ISSUE #307: [JExtract/JNI] Unable to map `UInt8` to Java
Source code at https://github.com/PureSwift/Bluetooth/pull/197

```
coleman@Alseys-MacBook-Pro Bluetooth % SWIFT_JAVA=1 swift build --target Bluetooth
[1/1] Planning build
Building for debugging...
Generated /Users/coleman/Developer/Bluetooth/.build/plugins/outputs/bluetooth/Bluetooth/destination/GenerateBluetoothDefinitions/DeclarationUUID.swift
Generated /Users/coleman/Developer/Bluetooth/.build/plugins/outputs/bluetooth/Bluetooth/destination/GenerateBluetoothDefinitions/UnitIdentifiers.swift
Generated /Users/coleman/Developer/Bluetooth/.build/plugins/outputs/bluetooth/Bluetooth/destination/GenerateBluetoothDefinitions/ServiceUUID.swift
Generated /Users/coleman/Developer/Bluetooth/.build/plugins/outputs/bluetooth/Bluetooth/destination/GenerateBluetoothDefinitions/DescriptorUUID.swift
Generated /Users/coleman/Developer/Bluetooth/.build/plugins/outputs/bluetooth/Bluetooth/destination/GenerateBluetoothDefinitions/CharacteristicUUID.swift
Generated /Users/coleman/Developer/Bluetooth/.build/plugins/outputs/bluetooth/Bluetooth/destination/GenerateBluetoothDefinitions/MemberUUID.swift
Generated /Users/coleman/Developer/Bluetooth/.build/plugins/outputs/bluetooth/Bluetooth/destination/GenerateBluetoothDefinitions/CompanyIdentifiers.swift
JExtractSwiftLib/JNISwift2JavaGenerator+JavaTranslation.swift:71: Fatal error: unsupported known type: uint8
[163/165] Generate Java wrappers for Swift types
```

### PR DESCRIPTION
**Pull request by ktoso**
Resolves #307 

This introduces `@Unsigned long` and friends importing as well as an opt-in mode to import unsigned types as Guava's `UnsignedInteger` and friends which is only available for FFM right now.

### CODE REVIEW

File: Sources/JavaKitConfigurationShared/GenerationMode.swift [hunk 1]
```diff
@@ -12,10 +12,55 @@
...
+public enum JExtractUnsignedIntegerMode: String, Codable {
+  /// Treat unsigned Swift integers as their signed equivalents in Java signatures,
+  /// however annotate them using the `@Unsigned` annotation which serves as a hint
+  /// to users of APIs with unsigned integers that a given parameter or return type
+  /// is actually unsigned, and must be treated carefully.
+  ///
+  /// Specifically negative values of a `@Unchecked long` must be interpreted carefully as
+  /// a value larger than the Long.MAX_VALUE can represent in Java. You can use `org.swift.swiftkit.core.primitives`
+  /// utility classes to work with such unsigned values in Java.
+  case annotate
```
Comment (ktoso) [inline Sources/JavaKitConfigurationShared/GenerationMode.swift:33]: That's our default mode, it's also similar to what OpenJDK jextract does (we add the annotation, jextract itself does nothing)

File: Tests/JExtractSwiftTests/UnsignedNumberTests.swift [hunk 2]
```diff
@@ -0,0 +1,268 @@
...
+          /* -> */SwiftValueLayout.SWIFT_UINT32
+          /* first: */SwiftValueLayout.SWIFT_UINT64
+          /* second: */SwiftValueLayout.SWIFT_UINT32
+        );
+        """,
+        """
+        @Unsigned
+        public static int unsignedLong(@Unsigned long first, @Unsigned int second) {
+          return swiftjava_SwiftModule_unsignedLong_first_second.call(first, second);
+        }
```
Comment (ktoso) [inline Tests/JExtractSwiftTests/UnsignedNumberTests.swift:263]: Showcase of the default extract mode -- we don't do any conversions, but we annotate the types for easier discovery in IDEs

Image

File: SwiftKitCore/src/main/java/org/swift/swiftkit/core/primitives/NullnessCasts.java [hunk 3]
```diff
@@ -0,0 +1,69 @@
+//===----------------------------------------------------------------------===//
```
Comment (ktoso) [inline SwiftKitCore/src/main/java/org/swift/swiftkit/core/primitives/NullnessCasts.java]: All the primitives types are vendored Guava types.

TBD if we'd like to may be just roll our own entirely or just make jextract emit code which assumes you'll bring your own Guava perhaps...

**Comment by ktoso** [comment]
I'm still on the fence about the `Unsigned...` wrapper types... This was originally the direction I pursued, but I think the annotate mode ended up more interesting.
In the end, we could also offer `kotlin.UShort` and unsigned types, which would be a different way to "wrap" that would be welcome on Android perhaps.

I'm gonna sleep over this change and decide that to do about the guava types -- perhaps remove them for now, until we truly want them after all.
