### PR TITLE
make `SwiftJava` a dynamic lib and add class lookup fallbacks

### LINKED ISSUE #419: `swift-java` does not work on Android API 28-30, due to missing JavaVM JNI symbols
Currently, `swift-java` can crash runtime for Android API 28-30, if you try to use the `JavaVirtualMachine` class. This means that any JExtract generated sources _(JNI mode)_ only works on API 31+, since we rely on `JavaVirtualMachine.shared().environment()`.

This is due to the fact that Android first added _official_ support for the JavaVM JNI functions, such as `JNI_GetCreatedJavaVMs`, in API 31+.
We rely on these methods for getting the active JavaVM, through for example `JavaVirtualMachine.shared()`.

We have a shim for these JNI functions in https://github.com/swiftlang/swift-java/blob/main/Sources/CSwiftJavaJNI/AndroidSupport.cpp - this works on API 31+, because those Android versions have the `libnativehelper.so`. Previous versions did not. We cannot load `libart.so` or `libdvm.so` instead, since previous Android versions restricted dynamically loading these "private" libraries.

It seems like the **recommended** solution to this issue on Android, is to tap into `JNI_OnLoad` and store the VM from there. This would mean that we would need to update the shared VM at runtime:
https://github.com/swiftlang/swift-java/blob/cc0ff8f6e478a05079c7206d7d4014d9c6eef776/Sources/SwiftJava/JavaKitVM/JavaVirtualMachine.swift#L223 

We need to figure out which library to dynamically load, that contains the `JNI_OnLoad` and can set the shared VM. My concern is since we already statically link the `SwiftJava` package _(the generated sources depend on it)_, it would not be OK to just also dynamically load it on the Java side, but I am **not** sure.

An alternative solution could be _(if this works in practice):_
1. Define a function in `SwiftJava` with `@_silgen_name("_swift_java_setSharedVM")`, which takes in a JavaVM and updates the shared one.
2. Call that function in `JNI_OnLoad` from the already dynamically loaded `SwiftRuntimeFunctions` target to set the shared VM.

### PR DESCRIPTION
**Pull request by madsodgaard**
Converts `SwiftJava` to a dynamic lib, that will be loaded in the JExtract libs. This will always us to tap into `JNI_OnLoad` to get the shared JVM, and also cache the application class loader, so that we can use that as a fallback in the `withJNIClass`, if for example running on a native thread.

Resolves #419

### CODE REVIEW

File: Sources/SwiftJava/AnyJavaObject.swift [hunk 1]
```diff
@@ -102,23 +102,39 @@ extension AnyJavaObject {
...
   private static func _withJNIClassFromCustomClassLoader<Result>(
     _ classLoader: JavaClassLoader,
     in environment: JNIEnvironment,
-    _ body: (jclass?) throws -> Result
+    _ body: (jclass) throws -> Result
   ) throws -> Result {
-    let resolvedClass = try? classLoader.findClass(fullJavaClassName)
-    return try body(resolvedClass?.javaThis)
+    let resolvedClass = try classLoader.findClass(fullJavaClassName)
+    return try body(resolvedClass!.javaThis)
```
Comment (ktoso) [inline Sources/SwiftJava/AnyJavaObject.swift:139]: mini comment here as we do the `!` please? cannot ever be null because it'll throw a not found?

File: Sources/SwiftJavaRuntimeSupport/generated/JavaSwiftArena.swift [hunk 2]
```diff
@@ -16,3 +16,11 @@ import SwiftJava
 
 @JavaInterface("org.swift.swiftkit.core.SwiftArena")
 public struct JavaSwiftArena {}
+
+extension JavaSwiftArena {
+  /// A cache for the default auto arena found in SwiftKitCore
+  public static internal(set) var defaultAutoArena: JavaSwiftArena = {
+    let swiftMemoryClass = try! JavaClass<SwiftJavaRuntimeSupport.JavaSwiftMemoryManagement>()
+    return swiftMemoryClass.defaultSwiftJavaAutoArena
```
Comment (ktoso) [inline Sources/SwiftJavaRuntimeSupport/generated/JavaSwiftArena.swift:24]: great, thx

File: Sources/SwiftJava/JNI.swift [hunk 3]
```diff
@@ -21,36 +20,28 @@ import CSwiftJavaJNI
...
-    let localObject = environment.interface.GetStaticObjectField(environment, swiftMemoryClass, arenaFieldID)!
-    self.defaultAutoArena = JavaSwiftArena(javaThis: localObject, environment: environment)
-    environment.interface.DeleteLocalRef(environment, localObject)
   }
 }
 
-// Called by generated code, and not automatically by Java.
-public func _JNI_OnLoad(_ javaVM: JavaVMPointer, _ reserved: UnsafeMutableRawPointer) {
+@_cdecl("JNI_OnLoad")
+func SwiftJava_JNI_OnLoad(javaVM: JavaVMPointer, reserved: UnsafeMutableRawPointer) -> jint {
```
Comment (ktoso) [inline Sources/SwiftJava/JNI.swift:44]: don't we need this "lower", in a lib that does not have macros?

Comment (ktoso) [reply Sources/SwiftJava/JNI.swift:44]: note, we'll do that later
