### PR TITLE
Fail Macro Expansion if JavaStaticField is used in non-class

### LINKED ISSUE #65: JavaKit's @JavaStaticField could detect that it should not be used on static field
Followup to https://github.com/swiftlang/swift-java/pull/61

> For bonus points, one could have the @JavaStaticField macro detect the static and produce an error diagnosing the problem, but it's not really necessary. Folks shouldn't have to write these macro uses themselves.

### PR DESCRIPTION
**Pull request by jrosen081**
Closes #65 

This adds support for failing macro expansion if `JavaStaticField` is used in the incorrect context.

One thing I was thinking is we can add similar logic for the `JavaStaticMethod` to fail in that context. That will fail in compilation, but it could be nicer to fail expansion vs fail in an implementation detail (of a function not existing on the type)

### CODE REVIEW

File: Sources/JavaKitMacros/JavaFieldMacro.swift [hunk 1]
```diff
@@ -79,4 +84,18 @@ extension JavaFieldMacro: AccessorMacro {
...
   }
+
+  private static func isInStaticContext(context: some MacroExpansionContext) -> Bool {
+    for lexicalContext in context.lexicalContext {
+      if let classSyntax = lexicalContext.as(ClassDeclSyntax.self) {
+        if classSyntax.name.trimmedDescription.starts(with: "JavaClass<") {
+          return true
+        } else {
+          return false
+        }
```
Comment (ktoso) [inline Sources/JavaKitMacros/JavaFieldMacro.swift]: that's just a `return classSyntax.name.trimmedDescription.starts(with: "JavaClass<")` right?

File: Sources/JavaKitMacros/JavaFieldMacro.swift [hunk 2]
```diff
@@ -79,4 +84,18 @@ extension JavaFieldMacro: AccessorMacro {
 
     return accessors
   }
+
+  private static func isInStaticContext(context: some MacroExpansionContext) -> Bool {
```
Comment (ktoso) [inline Sources/JavaKitMacros/JavaFieldMacro.swift]:
```suggestion
  private static func isInJavaClassContext(context: some MacroExpansionContext) -> Bool {
```

maybe? Not to be confused in being in some actual `static` etc.

**Review by ktoso — COMMENTED** [review]
looks good, minor comment

**Review by ktoso — APPROVED** [review]

**Comment by ktoso** [comment]
Tests failed, something isn't quite right:

```

/__w/swift-java/swift-java/Sources/JavaKit/generated/JavaBoolean.swift:31:3: error: Cannot use @JavaStaticField outside of a JavaClass instance (from macro 'JavaStaticField')
29 | }
30 | extension JavaClass<JavaBoolean> {
31 |   @JavaStaticField(isFinal: true)
   |   `- error: Cannot use @JavaStaticField outside of a JavaClass instance (from macro 'JavaStaticField')
32 |   public var TRUE: JavaBoolean!
33 | 
```

**Comment by jrosen081** [comment]
> Tests failed, something isn't quite right:
> 
> 
> 
> ```
> 
> 
> 
> /__w/swift-java/swift-java/Sources/JavaKit/generated/JavaBoolean.swift:31:3: error: Cannot use @JavaStaticField outside of a JavaClass instance (from macro 'JavaStaticField')
> 
> 29 | }
> 
> 30 | extension JavaClass<JavaBoolean> {
> 
> 31 |   @JavaStaticField(isFinal: true)
> 
>    |   `- error: Cannot use @JavaStaticField outside of a JavaClass instance (from macro 'JavaStaticField')
> 
> 32 |   public var TRUE: JavaBoolean!
> 
> 33 | 
> 
> ```

Oh my. I'm checking for classdecl, but I think I need to check for extensiondecl. I'll fix this up soon

File: Sources/JavaKitMacros/JavaFieldMacro.swift (hunk 2 above)
Comment (jrosen081) [reply Sources/JavaKitMacros/JavaFieldMacro.swift]: updated to use java class in this. I can see how static could be confusing since it meant static in the `java` form not the `swift`

**Review by ktoso — APPROVED** [review]
Nice, thank you very much!
